<?php
// $Id$

// Legal module
// Robert Castelo
// services@cortextcommunications.com

function legal_help($section = 'admin/help#legal') {
  $output = '';

  switch ($section) {
    case 'admin/modules#description':
      $output = t('Adds Terms & Conditions statement to registration page.');
      break;
     case 'admin/help#legal':
      $output .= "<p>Adds Terms & Conditions statement to registration page, requires visitor to accept T&C to register.</p>";
      $output .= "<p>When a user creates an account you can require them to accept your Terms & Conditions for use of the site.</p>";
      break;     
  }
  return $output;
}


function legal_perm() {
  return array('administer Terms and Conditions');
}



function legal_menu($may_cache) {

  $items = array();
  
  if ($may_cache) {      
   
     $items[] = array('path' => 'admin/settings/legal', 'title' => t('legal'), 'callback' => 'legal_page_admin', 'access' => user_access('administer Terms and Conditions'));
  }
  
  return $items;
}


function legal_page_admin() {

  $edit = $_POST['edit'];
  $operation = $_POST['op'];
  
  if ($operation == 'Save') {
    legal_validate_conditions($edit);
    $error = form_get_errors();
    if (!$error) {
        legal_save_conditions($edit);
        cache_clear_all();
        drupal_set_message (t('Terms & Conditions have been saved.'));
    }
  }
  
  $conditions_in_db = legal_get_conditions();
  $conditions = $conditions_in_db;
  
  if ($operation == 'Preview') {
    $conditions = $edit;
    legal_validate_conditions($edit);
    $output = '<h3>'. t('Preview') .'</h3>';
    $output .= '<fieldset><legend>Terms and Conditions of Use</legend>';
    $output .= legal_account_form($edit['conditions'], $edit['display'], 0, '', '-preview');
    $output .= '</fieldset>';
  }
  
  if ($conditions_in_db['tc_id']) {
    $output .= '<h4>' . t('Current Version') . '</h4><p><strong>' . t('Version ID:') . '</strong> ' . $conditions_in_db['tc_id'] . '<br /><strong>' . t('Last saved:') . '</strong> ' . date("l dS of F Y h:i:s A", $conditions_in_db['date']) . '</p>';
  } else {
    $output .= t('Terms & Conditions will not be shown to users, as no T&C have been saved.');
  }
  
  $output .= form_textarea(t('Terms & Conditions'), 'conditions', $conditions['conditions'], 70, 6, t('Your Terms & Conditions'), '', TRUE);
  $output .= form_radios(t('Display Style'), 'display', $conditions['display'], array(t('Scroll Box'), t('Scroll Box (CSS)'), t('HTML Text')), t('How terms & conditions should be displayed to users.'), TRUE);
  $output .= form_submit(t('Preview'));
  $output .= form_submit(t('Save'));
  
  print theme('page', form($output));
  return;
}


function legal_user($type, &$edit, &$user, $category = FALSE) {

    $edit['conditions'] = NULL;
    $account = $user;
    global $user;
    $conditions = legal_get_conditions();

    if ($conditions['conditions'] == NULL) {
      return array();
    } 
    
    switch ($type) {
      case 'register':
      
        $form = legal_account_form($conditions['conditions'], $conditions['display'], $edit['legal_accept']);
        return array(array('title' => t('Terms and Conditions of Use'), 'data' => $form, 'weight' => 0));
        
      case 'form':
        
        if ($category == 'account') {
            $legal_account= legal_get_accept($account->uid);
    
            // User is not account owner - disable checkbox
            if ($account->uid != $user->uid) {
                $read_only = array('disabled' => 'disabled');
            }
            
            // T&C has already been accepted - disable checkbox
            if ($legal_account->uid) {
                $read_only = array('disabled' => 'disabled');
                $accepted = 1;
            }
            
            $form = legal_account_form($conditions['conditions'], $conditions['display'], $accepted, $read_only);
            return array(array('title' => t('Terms and Conditions of Use'), 'data' => $form, 'weight' => 0));
        }
        
      case 'validate':
        // User account owner?
        // Unregistered user?
        if ($account->uid == $user->uid || $user->uid == 0) {
            
            // if already accepted skip validation
            $legal_account= legal_get_accept($account->uid);
            if ($legal_account->uid) break;
            
            if ($edit['legal_accept'] != '1' && $category == 'account') {
              form_set_error('legal_accept', t('You must <strong>accept</strong> the Terms & Conditions of Use.'));
            }
            
        }
        break;
       
    case 'update':
    case 'insert':
        
        $edit['legal_accept'] = NULL;
        // if already accepted skip data entry
        $legal_account= legal_get_accept($account->uid);
        if ($legal_account->uid) break;
        
        if ($account->uid == $user->uid || $user->uid == 0) {
            legal_save_accept($account->uid, $conditions['tc_id']);
        }
        break;
    }
    
    return;
  }
  
function legal_get_accept($uid) {

    $accept = db_fetch_object(db_query("SELECT * FROM {legal_accepted} WHERE uid = '%d' ORDER BY legal_id DESC LIMIT 1", $uid));
    return $accept;
}


function legal_save_accept($uid, $tc_id) {

  db_query("INSERT INTO {legal_accepted} (legal_id, uid, tc_id, accepted) VALUES (NULL, '%d', '%d', '%d')", $uid, $tc_id, time());

  return;
}

function legal_save_conditions($conditions) {

    variable_set('legal_display', $conditions['display']);
    
    // If new conditions are different from current permisions - enter in database
    $current_conditions = db_result(db_query("SELECT conditions FROM {legal_conditions} ORDER BY tc_id DESC LIMIT 1"));
    if ($current_conditions != $conditions['conditions']) {
        db_query("INSERT INTO {legal_conditions} (tc_id, conditions, date) VALUES (NULL, '%s', '%d')", $conditions['conditions'], time());
    }
    
  return;
}

function legal_get_conditions() {

    $conditions = db_fetch_array(db_query("SELECT * FROM {legal_conditions} ORDER BY tc_id DESC LIMIT 1"));
    $conditions['display'] = variable_get('legal_display', '0');
    return $conditions;
}

function legal_validate_conditions($edit) {

  if (!$edit['conditions']) form_set_error('conditions', t('Terms & Conditions must be entered.'));
  return;
}

function legal_account_form($conditions, $display_style, $accept, $read_only = '', $preview = '') {
    
    switch ($display_style) {
        case 1:
            $path = drupal_get_path('module', 'legal');
            drupal_set_html_head('<style type="text/css" media="all">@import "' . $path . '/legal/legal.css";</style>');
            $output = '<div class="legal-terms">' . $conditions . '</div>';
            break;
        case 2:
            $output = $conditions;
            break;
        default:
            $output = form_textarea('', 'conditions' . $preview, $conditions, 70, 10, '', array('readonly' => '', 'wrap' => 'virtual'));
    }
    
    $output .= form_checkbox(t('<strong>Accept</strong> Terms & Conditions of Use'), 'legal_accept', 1, $accept, '', $read_only, TRUE);
    
    return $output;
}

?>