<?php
// $Id$

function legal_system($field) {
  $system["description"] = t("Adds Terms & Conditions statement to profile.");
  $system["admin_help"] = t("When a user creates an account you can require them to accept your Terms & Conditions for use of the site<br />Notes:<ul><li>In order for a user to enter information you <b>must</b> check \"enable\".</li><li>In order for other people too see the entered information you must make it \"public\".</li><li>If an item is \"public\", but not enabled, the user can never give it a value and it will never be seen.  Public does <b>not</b> imply \"enable\".</li><li>If an item is enabled, but not shown in the registration form the user will have to ". l("edit their account", "user/edit") ." to place information in the field.</ul>");
  return $system[$field];
}

function legal_user($type, $edit, &$user) {
    // What type of registration action are we taking?
    switch ($type) {
      case t("register_form"):
        // Add three items to the resigtration form.
        $output .= form_item("Terms & Conditions of Use",
                             "<textarea name=\"conditions\" rows=\"10\" cols=\"70\" readonly wrap=\"virtual\">".
                             "ADD YOUR TERMS AND CONDITIONS HERE" . "</textarea>");
        $output .= form_checkbox("<strong>Accept</strong> Terms & Conditions of Use",
                                 legal_accept, 1, $edit["legal_accept"]);
        return $output;
      case t("register_validate"):
        // The user has filled out the form and checked the "accept" box.
        if ($edit["legal_accept"] == "1") {
          // on success return the values you want to store
          return array("legal_accept" => 1);
        }
        else {
          // on error return an error message
          return "You must <strong>accept</strong> the Terms & Conditions of Use to register.";
        }
    }
  }
  
  ?>