# Schema for the configuration files of the Legal module.

legal.settings:
  type: config_object
  label: 'Legal settings'
  mapping:
    legal_display:
      type: int
      label: 'Legal displa setting'
